### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThatGuyJamal** [oadpoaw/disclosure#17]
Invalid server link on read me, can you make a new one.

**Comment by Cedric2008** [comment]
Yeah, the server invite is invalid

**Comment by oadpoaw** [comment]
https://discord.gg/fJCfptzwjG . 

No clue why it was revoked, probably a bug in discord's end. I checked the audit logs, wasnt even useful after all. But yea, this is weird

**Comment by ThatGuyJamal** [comment]
> https://discord.gg/fJCfptzwjG .
> 
> No clue why it was revoked, probably a bug in discord's end. I checked the audit logs, wasnt even useful after all. But yea, this is weird

Thanks for the reply! I cant wait to test out this CLI, reminds me of slappy.
